fixes:  erdep audit, caches vs. interactive commands

diff --git a/nh b/nh
--- a/nh
+++ b/nh
@@ -778,10 +778,6 @@ cache_copy() {
         done
 	popd >/dev/null
 }
-cache_drop() {
-        local FIELD="$1"
-        rm -f ${PKGDB}/cache/*.${FIELD}
-}
 
 emit_explanation() {
         local over="$1"; shift
@@ -917,10 +913,8 @@ emit_overrides() {
         ### 1. Generate override cache
         ###
         if test -z "${reuse_cache}"
-        then
-                cache_drop override
-                cache ${require_descs} ${silent} ||
-                        fail "cache generation failed" >&2
+        then cache ${require_descs} ${silent} "$@" ||
+                 fail "cache generation failed" >&2
         fi
 
         echo -n "Assembling overrides.." >&2
@@ -1065,7 +1059,7 @@ override_builder() {
         do
                 echo -n "$(path ${LOGTY} ${over} ${attr})" > ${PKGDB}/current.build
                 nix-build ${NIX_GHC_PACKAGE_SET} -A ${erdep} ${NIX_BUILD_OPTIONS} 2>&1 \
-                        | set_stdin ${LOGTY} ${over}.erdeps ${attr}
+                        | set_stdin ${LOGTY} ${over} ${attr}
                 status=${PIPESTATUS[0]}
                 rm -f ${PKGDB}/current.build
                 if test ${status} != 0
@@ -1073,7 +1067,7 @@ override_builder() {
                         echo "FATAL: essential rev-dependency '${erdep}' breaks, without overriding '${attr}'s '${over}'" >&2
                         echo "FATAL: logs:  nh get ${LOGTY} ${over} ${attr}" >&2
                         _set ${FAILTY} ${over} ${attr} "ESSENTIAL-REVERSE ${erdep}"
-                        fail_classify_one_property ${over}.erdeps ${attr}
+                        fail_classify_one_property ${over} ${attr}
                         return 1
                 fi
         done
@@ -1905,7 +1899,7 @@ set-meta )         HELP "set-meta ATTR META VAL"   "Set a single metadata entry 
                    _set       def/meta  "$2" "$1" "$3";;
 
 chdir )            HELP "chdir ATTR SUBDIR"       "Change directory before build;  \"\" removes the override" || return 0
-                   _set def/meta chdir           "$1" "$2";   cache_gen_override_one "$1";;
+                   _set def/meta chdir           "$1" "$2";   overrides "$1";;
 
 section-overman )
 section "Override manipulation (low level)" \
@@ -1915,12 +1909,12 @@ section "Override manipulation (low level)" \
 disable )          HELP "disable ATTR[.OVER]"     "Disable all/single overrides for an attribute" || return 0
                    attr="$1"; over="${2:+.$2}"
                    _set       def/meta disable${over} "$attr" true
-                   cache_gen_override_one "$1";;
+                   overrides "$1";;
 
 enable )           HELP "enable ATTR[.OVER]"      "Re-enable previously disabled overrides" || return 0
                    attr="$1"; over="${2:+.$2}"
                    _set       def/meta disable${over} "$attr" ""
-                   cache_gen_override_one "$1";;
+                   overrides "$1";;
 
 set-explanation )  HELP "set-explanation ATTR OVER" "Provide a manual explanation for an override's existence" || return 0
                    attr="$1"; over="$2"
@@ -1938,38 +1932,38 @@ get )              HELP "get ATTR OVER"           "Get an attribute's override v
 
 set )              HELP "set ATTR OVER VAL"       "Set an attribute's override value;  \"\" removes the override" || return 0
                    _set       def/over  "$2" "$1" "$3"
-                   cache_gen_override_one "$1";;
+                   overrides "$1";;
 
 edit )             HELP "edit ATTR OVER"          "Edit the current attribute's value using readline" || return 0
                    edit                      "$1" "$2" "$3";;
 
 dontRevision )     HELP "edit ATTR OVER"          "Edit the current attribute's value using readline" || return 0
                    _set def/over revision        "$1" "null"
-                   _set def/over editedCabalFile "$1" "null"; cache_gen_override_one "$1";;
+                   _set def/over editedCabalFile "$1" "null"; overrides "$1";;
 
 check | doCheck )  HELP "check ATTR"              "Disable an existing dontCheck override" || return 0
-                   _set def/over doCheck         "$1";        cache_gen_override_one "$1";;
+                   _set def/over doCheck         "$1";        overrides "$1";;
 
 dontCheck )        HELP "dontCheck ATTR"          "Disable tests" || return 0
-                   _set def/over doCheck         "$1" false;  cache_gen_override_one "$1";;
+                   _set def/over doCheck         "$1" false;  overrides "$1";;
 
 haddock | doHaddock )
                    HELP "haddock ATTR"            "Disable an existing dontHaddock override" || return 0
-                   _set def/over doHaddock       "$1";        cache_gen_override_one "$1";;
+                   _set def/over doHaddock       "$1";        overrides "$1";;
 
 dontHaddock )      HELP "dontHaddock ATTR"        "Disable Haddock generation" || return 0
-                   _set def/over doHaddock       "$1" false;  cache_gen_override_one "$1";;
+                   _set def/over doHaddock       "$1" false;  overrides "$1";;
 
 jailbreak | doJailbreak )
                    HELP "jailbreak ATTR"          "Turn on jailbreaking" || return 0
-                   _set def/over jailbreak       "$1" true;   cache_gen_override_one "$1";;
+                   _set def/over jailbreak       "$1" true;   overrides "$1";;
 
 dontJailbreak )    HELP "dontJailbreak ATTR"      "Disable an existing jailbreak override" || return 0
-                   _set def/over jailbreak       "$1";        cache_gen_override_one "$1";;
+                   _set def/over jailbreak       "$1";        overrides "$1";;
 
 extraLibs )        HELP "extraLibs ATTR '[ .. ]'" \
                                                   "Specify extra dependencies;  \"\" removes the override" || return 0
-                   _set def/over extraLibs       "$1" "$2";   cache_gen_override_one "$1";;
+                   _set def/over extraLibs       "$1" "$2";   overrides "$1";;
 
 section-status )
 section "Attribute status classification" status ls-shadowed ls-hackaged ls-upstreamed ls-unmerged ls-config;;
@@ -1998,7 +1992,7 @@ section "Override manipulation (high-level)" hackage unmerged upstream;;
 hackage )	   HELP "hackage ATTR [RELEASE=upstream-latest]" "Set the source override to a Hackage release" || return 0
                    attr="$1"; release="${2:-$(get_upstream_release ${attr})}"
                    hackage "$attr" "$release"
-                   cache_gen_override_one "$attr";;
+                   overrides "$attr";;
 
 unmerged )	   HELP "unmerged ATTR USER PR# [REV=HEAD]"      "Set the source override to a 3rd-party Github commit" || return 0
                    attr="$1"; user="$2"; pr="$3"; rev="$4"
@@ -2006,14 +2000,14 @@ unmerged )	   HELP "unmerged ATTR USER PR# [REV=HEAD]"      "Set the source over
                            fail "Usage: $0 unmerged ATTR GH-USER PR-ID [GITREV]"
                    github "$attr" "$user" "$rev"
                    _set def/github pr "$(repoName "$attr")" "$pr"
-                   cache_gen_override_one "$attr";;
+                   overrides "$attr";;
 
 upstream )	   HELP "upstream ATTR [REV=HEAD]"               "Set the source override to an upstream Github commit" || return 0
                    attr="$1"; rev="$2"
                    repo=$(repoName ${attr})
                    user=$(get def/github upstream $repo)
                    github "$attr" "$user" "$rev"
-                   cache_gen_override_one "$attr";;
+                   overrides "$attr";;
 
 section-github )
 section "Github-based (unmerged/upstream) override manipulation" github-up set-pr set-upstream set-repoName;;
@@ -2021,12 +2015,12 @@ section "Github-based (unmerged/upstream) override manipulation" github-up set-p
 github-up )        HELP "github-up ATTR"                         "Bump a Github override to its latest HEAD" || return 0
                    attr="$1"; repo=$(repoName ${attr})
                    github "$repo" "$(get def/github user $repo)"
-                   cache_gen_override_one "$attr";;
+                   overrides "$attr";;
 
 set-upstream )     HELP "set-upstream ATTR GITHUB-USER"          "Specify an attribute's Github upstream username" || return 0
                    attr="$1"; upstream="$2"
                    _set def/github upstream $(repoName "$attr") "$upstream"
-                   cache_gen_override_one "$attr";;
+                   overrides "$attr";;
 
 set-pr )           HELP "set-pr ATTR PR#"                        "Set the PR# of an attribute's Github override" || return 0
                    attr="$1"; pr="$2"
@@ -2034,11 +2028,11 @@ set-pr )           HELP "set-pr ATTR PR#"                        "Set the PR# of
                    then _set def/github pr "$(repoName "$attr")" "$pr"
                    else fail "not unmerged: $attr"
                    fi
-                   cache_gen_override_one "$attr";;
+                   overrides "$attr";;
 
 set-repoName )     HELP "set-repoName ATTR REPO"                 "Set an attribute's Github repository name" || return 0
                    attr="$1"; repo="$2";     _set def/meta repoName "$attr" "$repo"
-                   cache_gen_override_one "$attr";;
+                   overrides "$attr";;
 
 section-build )
 section "Build & results" build log fail failure-type failure-log expression proof;;
@@ -2113,7 +2107,8 @@ show-trims )       HELP "show-trims" "Show the trim suggestion" || return 0
                    show_trims "$@";;
 
 execute-trims )    HELP "execute-trims" "Execute the suggestion" || return 0
-                   execute_trims "$@";;
+                   execute_trims "$@"
+                   overrides;;
 
 audit )            HELP "audit [--autofix] [--autoonly] [--skip-baseline] [--reuse-{overrides,cache}] [ATTR]" \
                            "Sanity check the overridden attrs (or specified subset).  --autofix applies suggestions" || return 0
@@ -2136,7 +2131,6 @@ overrides-descs )  HELP "overrides-descs"      "As overrides, but mandate that e
 
 cache )            HELP "cache [--require-descs]" \
                            "Regenerate override cache" || return 0
-                   if test -z "$*"; then cache_drop override; fi
                    cache "$@";;
 
 show-cache )       HELP "show-cache ATTR"      "Print the cached text of attribute's override (DEBUG)" || return 0
